-- CREATE TABLE account (
--                          username VARCHAR(250) PRIMARY KEY ,
--                          password VARCHAR(250) NOT NULL
-- );
--
-- CREATE TABLE movie (
--                        title VARCHAR(250) PRIMARY KEY ,
--                        genre VARCHAR(250) NOT NULL,
--                        length INT NOT NULL
-- );